### ISSUE TITLE
Export to PNG diagram too?

### ISSUE THREAD

**Issue by josephernest** [stared/keras-sequential-ascii#4]
Congrats @stared for this cool project!
Do you think you could do a version that outputs such 3D diagrams too?

![](https://i.stack.imgur.com/K9lmg.png)

Or do you know another library that takes a Keras `model` object as input, and that can output such diagrams?

**Comment by stared** [comment]
As the readme says, the project is discontinued. There is https://medium.com/inbrowserai/simple-diagrams-of-convoluted-neural-networks-39c097d2925b where I link to other libraries generating diagrams from deep learning networks.
